<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>onesetup</AssemblyName>
    <RootNamespace>OneSetup</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="sfx\7zSD.sfx" />
    <EmbeddedResource Include="sfx\7zSD.sfx" LogicalName="OneSetup.7zSD.sfx" />
  </ItemGroup>
</Project>
